Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -21,7 +21,7 @@ jobs:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
-        ref: ${{ github.head_ref }}  # Important for pull requests, defaults to the branch or commit that triggered the workflow for pushes
+        ref: ${{ github.event_name == 'pull_request' ? github.base_ref : github.ref }}
 
     - name: Set up Python
       uses: actions/setup-python@v3
@@ -57,9 +57,15 @@ jobs:
         git add pyproject.toml
         git commit -m "Bump version to $NEW_VERSION"
         git checkout -B "${{ github.ref_name }}"
-        git push origin "${{ github.ref_name }}"
-        git tag "v$NEW_VERSION"
-        git push origin "v$NEW_VERSION"
+        git pull --rebase origin "${{ github.ref_name }}"
+        if [ $? -eq 0 ]; then
+          git push origin "${{ github.ref_name }}"
+          git tag "v$NEW_VERSION"
+          git push origin "v$NEW_VERSION"
+        else
+          echo "Failed to rebase, please check for conflicts or remote changes."
+          exit 1
+        fi
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
